name: Deploy to Production

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    environment: production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=20.18.1'
          check-latest: true
          cache: 'npm'
          cache-dependency-path: router/package-lock.json
          
      - name: Install dependencies
        run: |
          cd router
          npm ci
          
      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          environment-url: https://apptron.dev
          environment: production
          initial-status: pending
          
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: 4.32.0
          command: deploy
