name: Build Kernel
on:
  push:
    branches:
      - main
    paths:
      - 'kernel/**'

jobs:
  build-amd64:
    name: Build Linux Kernel (amd64)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Display system information
        run: |
          uname -a

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push to GHCR
        uses: docker/build-push-action@v6
        with:
          context: kernel
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:kernel
  
  build-arm64:
    name: Build Linux Kernel (arm64)
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - name: Display system information
        run: |
          uname -a

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to GHCR
        uses: docker/build-push-action@v6
        with:
          context: kernel
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:kernel